### ISSUE TITLE
user management

### ISSUE THREAD

**Issue by tdiprima** [sharmalab/bindaas#10]
The screencast at the bottom of the [downloads](http://imaging.cci.emory.edu/wiki/display/BDS/Downloads) page recommends changing the password for the default user once logged in.

The problem is, there doesn't appear to be any way to do so.

Also, if you go to Administration -> User Account Management -> User Signup Notification, and click Enable, and restart Bindaas, I kinda expected there to also be a way to users to request signup.  And there doesn't appear to be.  Was this an artifact from being able to sign up with OpenID?

**Comment by pradeeban** [comment]
Yes, most segments of the screencasts are outdated, and some of them are obsolete for the master build (for example - on building Bindaas). Ignore the segments of the screencasts when they do not match with what you see in the Bindaas middleware.

I agree with your observation on the OpenID. It was supposed to be signing up with OpenID for these notifications. However, Google stopped supporting OpenID. We could maintain the Yahoo one. But we are not maintaining the support for OpenID even with Yahoo in the next release.
