### ISSUE TITLE
query operators

### ISSUE THREAD

**Issue by tdiprima** [sharmalab/bindaas#11]
Bindaas doesn't work with certain query operators, like `$regex` and `$exists`.  It would be nice to have this functionality.

**Comment by pradeeban** [comment]
$exists works actually.


{
	"_operation" : "find" ,
	"_operation_args" : {
							"query" : {'type': { $exists: false }} ,
							"fields" :{},
							"skip" : 0,
							"limit" : 1000
						}
} 
                  



Similarly, $gt works too.
{
    “_operation” : “find” ,
    “_operation_args” : {
                            “query” : {‘qty’: {$gt: 50}} ,
                            “fields” :{},
                            “skip” : 0,
                            “limit” : 1000
                        }
}

I am yet to test the $regex.

I am testing the master. Please try the above formats in whatever branch you are using. I believe it should work in older releases as well.

**Comment by pradeeban** [comment]
$regex works as well. A sample query that works:

{
    "_operation" : "find" ,
    "_operation_args" : {
                            "query" : {'item': {$in: [
    {$regex: "l", $options: "i"},
    {$regex: "mp", $options: "i"} ] }},
                            "fields" :{},
                            "skip" : 0,
                            "limit" : 1000,
"sort": {'qty':1}
                        }
}       


As in the previous cases, I think the reason $regex queries failed before was the use of wrong queries. Use it in the right format. This is a bit restrictive as we are dealing with Mongo and Json which are not super-supportive of regex. But with care, it should work.
