### ISSUE TITLE
Enable authentication for Mongo provider

### ISSUE THREAD

**Issue by pradeeban** [sharmalab/bindaas#35]
Currently, MySQL, Postgres, and Drill providers support authentication. But Mongo provider is assumed to have a Mongo data source with no authentication. We should make Bindaas have a user name and password for Mongo provider as optional fields.

**Comment by tushar-97** [comment]
I'd like to take up this issue, if no one else is working on it. Issue #44 will also be solved under the scope of this issue. Just wanted to know how the UI is rendered? I understand we use the DataSourceConfiguration bean to get the form values.

**Comment by pradeeban** [comment]
Your observation is right. #44 would be ideally resolved before this one. Check for Drill data provider and MySQL data provider in the UI and check their relevant source code. 

Pls fork the source code, and create a pull request against the dev branch from your forked dev branch (not from master to master or master to dev) once you have fixed the issue and performed adequate tests. 

Pls make sure only the necessary files are changed, and no other changes (such as changes to styles and unnecessary changes to import statements) are made.

**Comment by tushar-97** [comment]
Thanks for the quick reply. I also want to debug and am using IntelliJ. I run the server via `java -Dpid=BINDAAS_INSTANCE -Xmx1024m -jar org.eclipse.osgi_3.10.100.v20150529-1857.jar -console`.
However remote debugging via port 5005 is not working. Am I missing something?

**Comment by pradeeban** [comment]
How are you running the remote debugging? I did not do remote debugging recently. So I do not recall. But one thing I am certain is that you need additional flags to perform remote debugging on an OSGi framework or a web application.

I would recommend reading similar articles such as http://www.datazoo.de/articles/125/ to figure out the exact flags to enable the remote debugging on port 500.

**Comment by tushar-97** [comment]
I have had no success with the debugging aspect till now. How exactly are the values we fill in the form passed onto the variables in DataSourceConfiguration. I understand we are serializing to a json object and loading that, but what exactly initiates that? I have created getter/setters and will try and finish this ASAP.


![sT9I9JYIlNn4dTWlGOPu4Aw](https://user-images.githubusercontent.com/19520011/54310883-6ed2e900-45f9-11e9-9ae2-858b381efcaf.png)

**Comment by pradeeban** [comment]
I recommend you slice this into smaller tasks. That way, you could make incremental development, with 2 PRs.

1) If a Mongo data provider is defined with a user name and password, (and ideally, an authentication database, although it can take "admin" as the default option) in the .project file (they will reside in BINDAAS-BINARY-HOME/bin/projects folder), can you extract them and connect to an authenticated mongo database successfully? A call (can be tested via curl or any REST client, through the service url / use the :9099 port - not the dashboard) through a Bindaas project should fail when you try to connect to an authenticated Mongo database. With your fixes, it should produce the same output as in a mongo database with authentication disabled.

Ideally, you will extract the .project file in the Mongo provider classes (the 4 classes that you are already familiar with by now, through your other PR) to pass on the authentication headers.

2) Edit the dashboard interface (what you are doing already).
3) Connect 1) and 2).

I think, 1 is pretty straightforward and you may even manage to submit the first pull request just for that!

For 2 and 3, you should refer to how this is handled by the MySQL provider and Drill Provider. Make sure that the authentication parameters are optional. Drill provider code should help you with that as it takes them as optional parameters. 

Pls let me know if you need help with 1 or if I am not clear enough on that.

**Comment by tushar-97** [comment]
Regarding pt 1, I don't understand the relevance of the port 9099. I don't think we will be extracting the details from the .project explicitly right?

So I set the getter/setter for username/password in the DataSourceConfiguration.java file. These are returning the correct values. So basically I will just update all the calls to MongoClient and pass the login credentials.

These credentials are not necessary so there wont be any validation in the form and the code should work even when they are not specified.

**Comment by tushar-97** [comment]
I added authentication to MongoDBProvider only and tested that successfully. Now I am able to query for records even though I have not changed the code for MongoDBQueryHandler. That means it is able to query without any auth. Is this the expected behaviour?

**Comment by pradeeban** [comment]
Extract the contents of the attached zip into your running Bindaas' bin directory.
[bin.zip](https://github.com/sharmalab/bindaas/files/2963979/bin.zip)

The sample project in the attachment (sample.project) consists of a mysql provider and a mongo provider.

When you place them in your bindaas, you can invoke those Bindaas APIs as below.

curl localhost:9099/services/sample/mysql/query/find

curl localhost:9099/services/sample/mongo/query/find

Now, if your Mongo is authenticated, or MySQL is authenticated with a username and password other than that is specified, the query will fail.

The authentication details are specific to each project. You can share them across different Bindaas users (like I just shared with you).

Since it seems you have already completed the authentication, can you check whether the attached project file fails in your authenticated mongo instance, but works when you add the below properties to the project file (of course, add the correct values in place of yourauthenticationdb, yourusername, and yourpassword)?

        "authenticationdb": "yourauthenticationdb",
        "username": "yourusername",
        "password": "yourpassword",

**Comment by pradeeban** [comment]
The authentications are project specific. Therefore, we cannot set a global username/password for the data sources. Your Bindaas instance should be able to connect to different Mongo instances and that's why we read the authentication details and other project information from the .project files.

**Comment by tushar-97** [comment]
I used your .project file and got an authentication error as expected. However local database has different authentication measures (which I am not clear with) so I used the admin database and created a new database as well for testing purposes. I then created two separate providers and was able to run my queries successfully. I am assuming that the authenticationdb is same as the database details the user provides.

When you say "we read the authentication details and other project information from the .project files" this line does that for us right?
`DataSourceConfiguration configuration = GSONUtil.getGSONInstance().fromJson(dataSource, DataSourceConfiguration.class);`

**Comment by pradeeban** [comment]
"I am assuming that the authenticationdb is same as the database details the user provides."

This is a wrong assumption. The database and collection information the user currently provides is the database the user needs to query. Authentication database is an entirely different thing. It is by default, set to the "admin" database in Mongo. However, ideally, you can also make this as an input parameter where the user can mention which authentication database to authenticate (rather than keeping it to the default "admin").

Therefore, make sure that your database and authenticationdb are different (in other words, don't assume that the user data is in the admin database, or the authentication database).

Pls see - https://docs.mongodb.com/manual/tutorial/enable-authentication/

**Comment by tushar-97** [comment]
I have created a new branch for the fix. Could you test it out locally before I submit a PR? I did test it at my local system and all the four operations were working (also throwing error if user tried to delete with read access). I added a new field for authentication database as pointed out.

Branch: https://github.com/tushar-97/bindaas/tree/issue-35-fix

**Comment by pradeeban** [comment]
It looks to me like you are on the right track. But I have left several comments for improvement. Please fix them and let me know.

Most importantly, all these 3 new fields should be optional. A user can choose to not provide them and still the project should be a correct one. Check with the drill data source provider which also has optional fields.

If the user does not provide these optional fields, that project file will work on mongo databases without authentication.

If the user provides the correct authentication fields (authentication database, username, and password), it will connect with an authentication-enabled mongo database. It will fail, if the provided authentication is wrong or if the user did not provide the authentication.

**Comment by pradeeban** [comment]
Fixed in dev by @tushar-97 #66

**Comment by pradeeban** [comment]
This has broken backward compatibility with 3.3.x and earlier Bindaas versions. Now a project works if it is in the format:
{
  "profiles": {
    "PatientData": {
      "dataSource": {
        "host": "127.0.0.1",
        "port": "27017",
        "db": "SepsisApp",
        "collection": "patients",
        "authenticationDb": "admin",
        "username": "",
        "password": "",
        "initialize": true
      },


But does not work, if it is in the format (which is how Bindaas 3.3.x defines the projects)
{
  "profiles": {
    "PatientData": {
      "dataSource": {
        "host": "127.0.0.1",
        "port": "27017",
        "db": "SepsisApp",
        "collection": "patients",
        "initialize": true
},

Please fix so that Bindaas 3.4.x assumes empty values (no authentication) when these values are not provided.

**Comment by tushar-97** [comment]
It was being assumed that providing no credentials will create empty strings. Project files for Bindaas 3.4.x would actually have those as null. Necessary null checks have been added.

**Comment by pradeeban** [comment]
The issue was backward compatibility with mongo .project files created with/for 3.3.x. Now with your recent fixes, 3.4.3 fixes this backward compatibility issue.
