### ISSUE TITLE
Mongo search by _id does not work properly

### ISSUE THREAD

**Issue by pradeeban** [sharmalab/bindaas#36]
Sample input:
{
    "_operation" : "find" ,
    "_operation_args" : {
                            "query" : { '_id' : ObjectId("$id$") }
                        }
}
  
Output is empty.

However, if your query is
{
    "_operation" : "find" ,
    "_operation_args" : {
                            "query" : { '_id' : $id$) }
                        }
}
  
and your input for the id is "zzz" (string) or 111 (integer), it will work.
This is because (as per my current understanding) we treat _id just as any other parameter in Bindaas find API.

**Comment by birm** [comment]
It looks like the following works:
{
	"_operation" : "find" ,
	"_operation_args" : {
							"query" : { '_id' : {"$oid":"$id$"}} ,
							"limit" : 1
						}
}

**Comment by pradeeban** [comment]
Thanks for finding this out. Closing the issue now.
