### ISSUE TITLE
Mongodb-provider uses deprecated methods and classes

### ISSUE THREAD

**Issue by pradeeban** [sharmalab/bindaas#44]
There are a few deprecated method usages in MongoDBQueryHandler and MongoDBSubmitHandler.

Use of Mongo should be replaced by MongoClient and MongoOptions by MongoClientOptions respectively.

**Comment by deepakkavoor** [comment]
I would like to work on this issue.

**Comment by pradeeban** [comment]
That's great to hear. Pls fork this repository and work on it. When you have made progress, you can submit a pull request for a review. In this process, if you need any help, feel free to get back to me.

**Comment by pradeeban** [comment]
@deepakkavoor, I would also recommend you work on the dev branch. We avoid creating pull requests directly against the master.

**Comment by tushar-97** [comment]
@pradeeban I have created a pull request for this fix. Also the method `getDb()` is deprecated. We use `getDatabase()` in the latest API? Should that be changed too?

**Comment by pradeeban** [comment]
As you observed, this issue was blocking #35. Your pull request seems to address this pre-requisite. 

http://mongodb.github.io/mongo-java-driver/3.9/driver/tutorials/authentication/

I don't think getDb() has any influence or negative effect on #35. It will be still nice to fix that. But probably you can prioritize #44 due to its relevance/importance.

**Comment by tushar-97** [comment]
I will work on #35 now. I have exams for the next 7-10 days due to which it is taking longer than expected. I hope there are no issues for this PR.

**Comment by pradeeban** [comment]
Perfect. Good luck with your exams. I will go through the PR shortly.

**Comment by pradeeban** [comment]
@tushar-97 Thanks for your PR. It is merged. However, it fixes only 2 of the 4 classes (Therefore, this issue remains open). We need to fix this for all the 4 classes, responsible for the GET, POST, PUT, and DELETE and also enable authentication for all the cases (eventually).

**Comment by tushar-97** [comment]
Thanks @pradeeban! I thought only the files mentioned in the description needed to be changed. I have created a new PR with the required changes.

**Comment by pradeeban** [comment]
Right, my bad. When I wrote the bug report, I was planning to implement it sooner. Did not pay enough attention to make the description complete. Thanks, @tushar-97.

**Comment by pradeeban** [comment]
Merged the relevant commits from @tushar-97 to dev.
