### ISSUE TITLE
Images for Wiki

### ISSUE THREAD

**Issue by sharmaashish** [sharmalab/bindaas#5]
![CodeDirectoryStructure](https://user-images.githubusercontent.com/8442831/27153412-5250eb2c-511f-11e7-9d9f-53cb8a4270de.png)
![Bindaas Plugins](https://user-images.githubusercontent.com/8442831/27154101-d137b5ae-5121-11e7-8cb6-3106e9b6b85c.png)
![Landing Page](https://user-images.githubusercontent.com/8442831/27154119-df78d008-5121-11e7-8fa1-d0ca7ee3ee04.png)

**Comment by pradeeban** [comment]
Closing this issue as the images are now used in the wiki - https://github.com/sharmalab/bindaas/wiki/Extending-Bindaas

**Comment by pradeeban** [comment]
<img width="770" alt="screen shot 2018-07-10 at 10 29 25 am" src="https://user-images.githubusercontent.com/225631/42516824-73622a92-842c-11e8-8cc5-87c402d1867a.png">

**Comment by pradeeban** [comment]
<img width="1239" alt="screen shot 2018-07-10 at 10 36 06 am" src="https://user-images.githubusercontent.com/225631/42517274-55d54274-842d-11e8-9a8a-8c7e794863de.png">

**Comment by pradeeban** [comment]
<img width="1169" alt="tcia-swagger" src="https://user-images.githubusercontent.com/225631/44429294-ef9a9c80-a564-11e8-9332-d6fb6234c036.png">

**Comment by pradeeban** [comment]
![1](https://user-images.githubusercontent.com/225631/44537779-a6b22780-a6cd-11e8-857c-8bf6c4986ae2.jpeg)

**Comment by pradeeban** [comment]
![6914056](https://user-images.githubusercontent.com/225631/44538540-99963800-a6cf-11e8-8c92-7582ba615436.png)
![6914057](https://user-images.githubusercontent.com/225631/44538541-99963800-a6cf-11e8-8f2e-e17b870f190d.png)
![6914058](https://user-images.githubusercontent.com/225631/44538542-99963800-a6cf-11e8-84a0-f542ecda061c.png)

**Comment by pradeeban** [comment]
<img width="541" alt="7831555" src="https://user-images.githubusercontent.com/225631/44552646-ea6e5680-a6f8-11e8-969d-e9f07ebc3725.png">

**Comment by pradeeban** [comment]
[7831554.jar.zip](https://github.com/sharmalab/bindaas/files/2316248/7831554.jar.zip)

**Comment by pradeeban** [comment]
[apikey.jar.zip](https://github.com/sharmalab/bindaas/files/2316254/apikey.jar.zip)

**Comment by pradeeban** [comment]
![10125357](https://user-images.githubusercontent.com/225631/44588870-ec7df700-a784-11e8-8624-8ec55f366de3.png)
![10125359](https://user-images.githubusercontent.com/225631/44588871-ed168d80-a784-11e8-9c23-f7ccb655417e.png)
![10125360](https://user-images.githubusercontent.com/225631/44588872-ed168d80-a784-11e8-9adf-8930f053792b.png)
