### ISSUE TITLE
Instructions - feedback button

### ISSUE THREAD

**Issue by tdiprima** [sharmalab/bindaas#9]
The instructions on the [downloads](http://imaging.cci.emory.edu/wiki/display/BDS/Downloads)) page say:

> If you have any questions, encounter bugs, or wish to provide feedback, please use the Feedback button in Bindaas. On the lower right corner of every Bindaas page you will see a link to a Bug/Feedback form that directly feeds into our issue tracker. This link is also available on this page (see the lower right corner).

The problem is, there is neither a feedback button in Bindaas nor is there one on the instructions page.  So that particular instruction should probably be removed. :)

**Comment by pradeeban** [comment]
Outdated documentation. There is no feedback button. The wiki is down and our plan is probably to move the new documentation elsewhere (such as https://github.com/sharmalab/bindaas/wiki).
