### ISSUE TITLE
Support Mongo Aggregate operation.

### ISSUE THREAD

**Issue by pradeeban** [sharmalab/bindaas#99]
Currently only find, count, distinct, group, and mapreduce are supported.

Mongo aggregate is a commonly used collection method. This must be supported.

**Comment by Raj2367** [comment]
I want to work on this. Please explain this issue.

**Comment by pradeeban** [comment]
1) First, please get familiar with writing Bindaas queries.

For example: sample find queries at https://github.com/sharmalab/bindaas/wiki/Support-to-Query-and-Projection-Operators

Similarly, the mongo operations count, distinct, and group are supported by Bindaas as well (samples can be found from the Bindaas admin console itself).

2) Once you are familiar with Bindaas and Bindaas projects (please proceed to the second step only after you complete the first step), attempt to fix this issue.

Mongo aggregate is not supported (https://docs.mongodb.com/manual/reference/method/db.collection.aggregate/) by Bindaas.

The task is to provide this support (and incorporate the relevant changes into the Bindaas web console user interface as well). You can start with the simplest of the aggregate queries.

**Comment by rpjayasekara** [comment]
If no one is working I would like to work on this

**Comment by rpjayasekara** [comment]
I will start with supporting an aggregate query like this
`db.orders.aggregate([
                     { $match: { status: "A" } },
                     { $group: { _id: "$cust_id", total: { $sum: "$amount" } } },
                     { $sort: { total: -1 } }
                   ])`
but I am not sure, how the Bindaas query template for aggregate should be. I have a template in my mind.
`{
	"_operation" : "aggregate" ,
	"_operation_args" : {
							"match" : { status: "A" }  ,
							"group" : { _id: "$cust_id", total: { $sum: "$amount" } } ,
							"sort" :  { total: -1 }
						}
}`

**Comment by pradeeban** [comment]
You can start with a simple one as you proposed. Once you have something working (that would at least have proven your effort on this), we can look into generalizing it later.
